name: Sync all branches to GitLab

on:
    push:
      branches:
        - "**"
    pull_request:
      branches:
        - "**"
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run GitHub to GitLab Sync Action
        uses: eskopp/github-to-gitlab-sync@main
        with:
          git_username: "ZXNrb3Bw"
          git_email: "c2tvcHAuZXJpa0BnbWFpbC5jb20="
          gitlab_repo: "aHR0cHM6Ly9naXRsYWIuZXJpay1za29wcC5kZS9naXRodWIvZ2l0aHViLXRvLWdpdGxhYi1lbnRyeXBvaW50LmdpdA=="
          gitlab_token: ${{ secrets.GITLAB }}
          base64: "true"
          github_token: ${{ secrets.GITHUB }}
